name: "Build Token Plugin Package"

on:
  workflow_call:
    inputs:
      GITHUB_REPOSITORY_NAME:
        required: true
        type: string
      UBUNTU_VERSION:
        required: true
        type: string
      isDev:
        required: false
        default: true
        type: boolean

jobs:
  timestamp:
    name: Get timestamp
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.timestamp.outputs.timestamp }}
    steps:
      - id: timestamp
        run: |
          export timestamp=$(date +%s)
          echo "timestamp=$timestamp" >> $GITHUB_OUTPUT
          echo "::group::DEBUG"
          echo "timestamp=$timestamp"
          echo "::endgroup::"

  get-deb-version:
    name: Get deb Package Version
    needs: timestamp
    runs-on: ubuntu-20.04
    outputs:
      deb-package-verion: ${{ steps.version.outputs.debVersion }}
    steps:

      - name: adding github workspace as safe directory
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Set up python
        run: |
          pip3 install semver

      - name: Set Version with UX-timestamp
        if: ${{ inputs.isDev }}
        run: python3 updateVersion.py --timestamp ${{ needs.timestamp.outputs.timestamp }}

      - name: Get current Version
        id: version
        run: |
          version=$(python3 updateVersion.py --getVersion)
          debVersion=$(sed -r "s/-/~/g" <<< $version)
          echo "debVersion=$debVersion" >> $GITHUB_OUTPUT

  build_token_plugin_release:
    name: Token Plugin Build Packages
    needs: [ timestamp, get-deb-version ]
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/${{ inputs.GITHUB_REPOSITORY_NAME }}/token-plugin-build:${{ inputs.UBUNTU_VERSION }}
    env:
      DEB_VERSION: ${{ needs.get-deb-version.outputs.deb-package-verion }}
    steps:
      - name: adding github workspace as safe directory
        run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set Version with UX-timestamp
        if: ${{ inputs.isDev }}
        run: python3 updateVersion.py --timestamp ${{ needs.timestamp.outputs.timestamp }}
      - name: Get current Version
        id: version
        run: |
          if [ -f "$GITHUB_OUTPUT" ]; then
            echo "The file, $GITHUB_OUTPUT, exists."
          else
            echo "The file, $GITHUB_OUTPUT, does not exist."
          fi

          version=$(python3 updateVersion.py --getVersion)
          echo "version: ${version}"
          debVersion=$(echo $version | sed -r 's/-/~/g')
          echo "debVersion: ${debVersion}"
          echo "debVersion=${debVersion}" >> $GITHUB_OUTPUT

      - name: Get indy-node version to depend on
        id: node-version
        shell: bash
        run: |
          version=$(grep -oP "\d+.\d+.\d+((-|.)?rc\d+)?" <<< $(grep -oP "indy-node==\d+.\d+.\d+((-|.)?rc\d+)?" sovtokenfees/setup.py) || true)
          echo $version > indy-node-version.txt
          echo "nodeVersion=$(sed 's/\./\~/3' indy-node-version.txt)" >> $GITHUB_OUTPUT
      - name: Build Token Plugin deployment package
        run: |
          mkdir -p /tmp/build-output
          fpm  --input-type dir --output-type deb --name sovtoken --architecture amd64 --maintainer "Sovrin" --no-python-fix-name  --version ${{ steps.version.outputs.debVersion }} --depends "indy-node(=${{ steps.node-version.outputs.nodeVersion }})" --verbose --no-python-dependencies --after-install ./devops/build-scripts/focal/sovtoken/postinst --before-remove ./devops/build-scripts/focal/sovtoken/prerm --exclude "*.pyo" --exclude "*.pyc" --no-python-fix-dependencies --python-bin "/usr/bin/python3" --force  sovtoken/
          fpm  --input-type dir --output-type deb --name sovtokenfees --architecture amd64 --maintainer "Sovrin" --no-python-fix-name  --version ${{ steps.version.outputs.debVersion }} --depends "indy-node(=${{ steps.node-version.outputs.nodeVersion }})" --verbose --no-python-dependencies --after-install ./devops/build-scripts/focal/sovtokenfees/postinst --before-remove ./devops/build-scripts/focal/sovtokenfees/prerm --exclude "*.pyo" --exclude "*.pyc" --no-python-fix-dependencies --python-bin "/usr/bin/python3" --force  sovtokenfees/
          mv ./*.deb /tmp/build-output
      - name: Upload sovtoken-deb
        uses: actions/upload-artifact@v3
        with:
          name: sovtoken-deb
          path: /tmp/build-output/sovtoken_*.deb
      - name: Upload sovtokenfees-deb
        uses: actions/upload-artifact@v3
        with:
          name: sovtokenfees-deb
          path: /tmp/build-output/sovtokenfees_*.deb

  build_sovtoken_pypi:
    name: sovtoken Build Package
    runs-on: ubuntu-20.04
    needs: timestamp
    container:
      image: ghcr.io/${{ inputs.GITHUB_REPOSITORY_NAME }}/token-plugin-build:${{ inputs.UBUNTU_VERSION }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set Version with UX-timestamp
        if: ${{ inputs.isDev }}
        run: python3 updateVersion.py --timestamp ${{ needs.timestamp.outputs.timestamp }}
      - name: Build python sovtoken package
        run: python3 sovtoken/setup.py sdist --dist-dir /tmp/dist bdist_wheel --dist-dir /tmp/dist
      - uses: actions/upload-artifact@v3
        with:
          name: sovtoken-python
          path: /tmp/dist
          retention-days: 5

  build_sovtokenfees_pypi:
    name: sovtokenfees Build Packages
    runs-on: ubuntu-20.04
    needs: timestamp
    container:
      image: ghcr.io/${{ inputs.GITHUB_REPOSITORY_NAME }}/token-plugin-build:${{ inputs.UBUNTU_VERSION }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set Version with UX-timestamp
        if: ${{ inputs.isDev }}
        run: python3 updateVersion.py --timestamp ${{ needs.timestamp.outputs.timestamp }}
      - name: Build python sovtokenfees package
        run: python3 sovtokenfees/setup.py sdist --dist-dir /tmp/dist bdist_wheel --dist-dir /tmp/dist
      - uses: actions/upload-artifact@v3
        with:
          name: sovtokenfees-python
          path: /tmp/dist
          retention-days: 5